#BinaryPath: 'C:\dont_scan\mylove.exe'
#BinaryPath: 'C:\Users\ayoul3\Documents\go\test\test.exe'
#BinaryPath: 'res\cmdLineW.exe'
BinaryPath: 'res\sock_static_file.exe'
ReflectArgs: '' # arg[0] is the program's name
ReflectMethod: function  # wait or function
LogLevel: 2