#BinaryPath: 'res\stripped_go.exe'
#BinaryPath: 'C:\Users\ayoul3\Documents\go\test\main.exe'
#BinaryPath: 'res\cmdLineW.exe'
#BinaryPath: 'res\sock_file.exe'
#BinaryPath: 'res\sock_static_file.exe'
BinaryPath: 'whatever.exe'
ReflectArgs: 'heyho' # arg[0] is the program's name
ReflectMethod:  # wait, function or empty
LogLevel: 2
Keywords:
  - mimikatz
  - delpy
  - benjamin
  - delpy